language: node_js
branches:
    only:
        # This is where pull requests from "bors r+" are built.
        - staging
        # This is where pull requests from "bors try" are built.
        - trying
        - master
sudo: false
node_js:
    - "8"
    - "10"
before_install:
    - npm install -g npm@6
install:
    # Install all dependencies
    - npx lerna bootstrap
script:
    - npm test
    - npm run lint
    - npm run format -- --list-different

jobs:
    include:
        # Define the release stage that runs semantic-release
        - stage: release
          node_js: lts/*
          script: skip
          git:
              depth: false
          deploy:
              provider: script
              on:
                  branch: master
              skip_cleanup: true
              script:
                  - bash deploy.sh
